class_name AssetPaths
extends RefCounted
## Resolves a logical art path to production or placeholder art.
##
## Two trees, kept strictly apart:
##
##   assets/art/production/   PixelLab-generated, reviewed and approved
##   assets/art/placeholder/  generated by tools/pixelart, stands in until then
##
## Production always wins. A logical path like
## "aircraft/trailhopper_4/trailhopper_4_side.png" resolves to the production
## file if one exists and the placeholder otherwise, so approving an asset is
## dropping it into the production tree — no code change, no path edits, and the
## game keeps running throughout the migration.
##
## Nothing in the engine should reference either tree directly.

const PRODUCTION_ROOT := "res://assets/art/production/"
const PLACEHOLDER_ROOT := "res://assets/art/placeholder/"

static var _cache: Dictionary = {}

static func resolve(logical: String) -> String:
    if _cache.has(logical):
        return _cache[logical]
    var production: String = PRODUCTION_ROOT + logical
    var chosen: String = production if ResourceLoader.exists(production) \
        else PLACEHOLDER_ROOT + logical
    _cache[logical] = chosen
    return chosen

## True when the approved asset is in place; used by the art status report.
static func is_production(logical: String) -> bool:
    return resolve(logical).begins_with(PRODUCTION_ROOT)

static func exists(logical: String) -> bool:
    return ResourceLoader.exists(resolve(logical))

static func load_texture(logical: String) -> Texture2D:
    var path: String = resolve(logical)
    return load(path) if ResourceLoader.exists(path) else null

## Non-texture assets (font descriptors, sprite anchor metadata) that still need
## the same production-over-placeholder rule.
static func resolve_file(logical: String) -> String:
    var production: String = PRODUCTION_ROOT + logical
    if FileAccess.file_exists(production):
        return production
    return PLACEHOLDER_ROOT + logical

## Called by tests after art is added, so a stale cache cannot mask a new asset.
static func clear_cache() -> void:
    _cache.clear()
