"""Deterministic pixel-art asset pipeline for Pixel Skies.

Every shipped sprite, tile and UI frame is generated by this package. Assets are
drawn on an exact integer pixel grid from a locked palette with hard edges and
binary alpha — see docs/PIXEL_STYLE_GUIDE.md, which this code implements.
"""
